### ISSUE TITLE
Key must be 32 bytes error

### ISSUE THREAD

**Issue by mustaqiimuhar** [tonytonyjan/rack_encrypted_cookie#1]
Hi,

I'm currently having this error `Unexpected error while processing request: key must be 32 bytes`. Is this something to do with the secrets? I'm using the latest Sinatra with this code snippet. Not sure if I've pass the required parameter for the gem to work. Hope you can help out! :)
```
set :sessions, true
set :session_store, Rack::Session::EncryptedCookie
set :session_secret, SecureRandom.hex(64)
```

**Comment by mustaqiimuhar** [comment]
Remediated the issue with this 
```
set :sessions, :key_size => 32, :salt => SecureRandom.hex(32), :signed_salt => SecureRandom.hex(32)
set :session_store, Rack::Session::EncryptedCookie
```

**Comment by tr4wzified** [comment]
Thanks for leaving the fix, helped me
